[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "udm-directory-connector"
version = "0.1.0"
description = "UDM connector for LDAP source directories"
readme = "README.md"
authors = [
  {name = "Univention GmbH", email = "packages@univention.de"},
]
# license = "GNU Affero General Public License v3"
keywords = []


requires-python = ">=3.10"
dependencies = [
    "certifi",
    "junkaptor>=0.0.5",
    "phonenumbers",
    "python-ldap",
    "requests",
    "strictyaml"
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]

[tool.hatch.build]
include = [
    "udm_directory_connector",
]

[project.urls]
Homepage = "https://git.knut.univention.de:univention/nubus/udm-directory-connector"

[project.scripts]
udm-directory-connector = "udm_directory_connector.__main__:cli"

[tool.tox]
requires = ["tox>=4.0.0"]
env_list = ["py311"]

[tool.tox.testenv.py311]
description = "Run unittests under Python 3.11"
commands = [
    "python -W error -I -bb -m unittest"
]
setenv = [
    "LDAPNOINIT=1",
    "LDAPTLS_CRLCHECK=none",
    "SASL_CONF_PATH=tests/sasl2/slapd.conf",
    "COVERAGE_FILE={envdir}/.coverage"
]
passenv = [
    "BIN",
    "SCHEMA",
    "SLAPD",
    "LDAP0_TRACE_LEVEL",
    "SLAPD_LOGLEVEL",
    "START_SLEEP",
    "LDAP0_LOG_LEVEL",
    "TMP",
    "LIBLDAP0_DEFINES",
    "LIBLDAP0_EXTRA_COMPILE_ARGS",
    "LIBLDAP0_EXTRA_LINK_ARGS",
    "LIBLDAP0_EXTRA_OBJECTS",
    "LIBLDAP0_INCLUDE_DIRS",
    "LIBLDAP0_LIBRARY_DIRS",
    "LIBLDAP0_LIBS"
]

[tool.ruff]
target-version = "py311"
line-length = 120

extend-select = ["I"]  # activate isort

[tool.ruff.isort]
known-first-party = ["slapdsock", "univention"]
