# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2024 Univention GmbH

---
kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: {{ include "common.names.fullname" . | quote }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "common.labels.standard" ( dict "customLabels" .Values.additionalLabels "context" $ ) | nindent 4 }}
  {{- if .Values.additionalAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.additionalAnnotations "context" . ) | nindent 4 }}
  {{- end }}
data:
  LOG_LEVEL: {{ .Values.config.logLevel | required ".Values.config.LogLevel is required" | quote }}
  {{- if .Values.config.loggingConfig }}
  LOG_CONF: {{ .Values.config.loggingConfig | quote }}
  {{- end }}
  REPEAT: {{ .Values.config.repeat | required ".Values.config.repeat is required" | quote }}
  REPEAT_DELAY: {{ .Values.config.repeatDelay | required ".Values.config.repeatDelay is required" | quote }}
  CONFIG_FILENAME: "/etc/directory-importer/config.yaml"
